name: FTSSkills
main: de.afgmedia.ftsskills.main.Skills
author: halberfan | AfGMedia
version: "1.2"
api-version: "1.15"

commands:
  ftsskills:
    aliases:
      - skill
      - skills
  ftsskillsadmin:
  inspizieren:
