name: FTSSkills
main: de.afgmedia.ftsskills.main.Skills
author: halberfan | AfGMedia
version: ${project.version}
api-version: "1.21"

commands:
  ftsskills:
    aliases:
      - skill
      - skills
  ftsskillsadmin:
    permission: ftsskills.admin
  inspizieren:
    description: "Schaue dir die Skills einer Person in deiner Nähe an"
